---
title: '2024-03-26 Ticker Selection from ETFDB'
date: 2024-03-26
permalink: /posts/2024/03/Ticker-Selection-from-ETFDB/
tags:
  -ETFdB Ticker screen
  - tickres
  - updated on 2024-03-26
---
** This is the rank list for maximum hold by 2500+ ETFs.  ** 





|      |   Column1 | Symbol       |   Counts | Finance Link                                                            |
|-----:|----------:|:-------------|---------:|:------------------------------------------------------------------------|
|    0 |         1 | MSFT         |      291 | [MSFT](https://finance.yahoo.com/quote/MSFT/financials)                 |
|    1 |         2 | NVDA         |      289 | [NVDA](https://finance.yahoo.com/quote/NVDA/financials)                 |
|    2 |         3 | AAPL         |      254 | [AAPL](https://finance.yahoo.com/quote/AAPL/financials)                 |
|    3 |         4 | META         |      235 | [META](https://finance.yahoo.com/quote/META/financials)                 |
|    4 |         5 | AMZN         |      233 | [AMZN](https://finance.yahoo.com/quote/AMZN/financials)                 |
|    5 |         6 | GOOGL        |      220 | [GOOGL](https://finance.yahoo.com/quote/GOOGL/financials)               |
|    6 |         7 | AVGO         |      218 | [AVGO](https://finance.yahoo.com/quote/AVGO/financials)                 |
|    7 |         8 | V            |      178 | [V](https://finance.yahoo.com/quote/V/financials)                       |
|    8 |        10 | JPM          |      168 | [JPM](https://finance.yahoo.com/quote/JPM/financials)                   |
|    9 |         9 | LLY          |      168 | [LLY](https://finance.yahoo.com/quote/LLY/financials)                   |
|   10 |        11 | GOOG         |      158 | [GOOG](https://finance.yahoo.com/quote/GOOG/financials)                 |
|   11 |        12 | TSLA         |      154 | [TSLA](https://finance.yahoo.com/quote/TSLA/financials)                 |
|   12 |        13 | UNH          |      151 | [UNH](https://finance.yahoo.com/quote/UNH/financials)                   |
|   13 |        14 | XOM          |      148 | [XOM](https://finance.yahoo.com/quote/XOM/financials)                   |
|   14 |        15 | BRK.B        |      147 | [BRK.B](https://finance.yahoo.com/quote/BRK.B/financials)               |
|   15 |        16 | MA           |      114 | [MA](https://finance.yahoo.com/quote/MA/financials)                     |
|   16 |        17 | JNJ          |      104 | [JNJ](https://finance.yahoo.com/quote/JNJ/financials)                   |
|   17 |        18 | ASML         |       97 | [ASML](https://finance.yahoo.com/quote/ASML/financials)                 |
|   18 |        19 | ABBV         |       92 | [ABBV](https://finance.yahoo.com/quote/ABBV/financials)                 |
|   19 |        20 | HD           |       89 | [HD](https://finance.yahoo.com/quote/HD/financials)                     |
|   20 |        21 | PG           |       86 | [PG](https://finance.yahoo.com/quote/PG/financials)                     |
|   21 |        22 | NOVN         |       81 | [NOVN](https://finance.yahoo.com/quote/NOVN/financials)                 |
|   22 |        23 | NOVO.B       |       80 | [NOVO.B](https://finance.yahoo.com/quote/NOVO.B/financials)             |
|   23 |        25 | ROG          |       75 | [ROG](https://finance.yahoo.com/quote/ROG/financials)                   |
|   24 |        24 | NFLX         |       75 | [NFLX](https://finance.yahoo.com/quote/NFLX/financials)                 |
|   25 |        28 | TTE          |       73 | [TTE](https://finance.yahoo.com/quote/TTE/financials)                   |
|   26 |        27 | CRM          |       73 | [CRM](https://finance.yahoo.com/quote/CRM/financials)                   |
|   27 |        26 | CVX          |       73 | [CVX](https://finance.yahoo.com/quote/CVX/financials)                   |
|   28 |        29 | AMD          |       72 | [AMD](https://finance.yahoo.com/quote/AMD/financials)                   |
|   29 |        30 | CSCO         |       71 | [CSCO](https://finance.yahoo.com/quote/CSCO/financials)                 |
|   30 |        32 | MRK          |       70 | [MRK](https://finance.yahoo.com/quote/MRK/financials)                   |
|   31 |        31 | COST         |       70 | [COST](https://finance.yahoo.com/quote/COST/financials)                 |
|   32 |        33 | SHEL         |       69 | [SHEL](https://finance.yahoo.com/quote/SHEL/financials)                 |
|   33 |        36 | WMT          |       66 | [WMT](https://finance.yahoo.com/quote/WMT/financials)                   |
|   34 |        35 | NESN         |       66 | [NESN](https://finance.yahoo.com/quote/NESN/financials)                 |
|   35 |        34 | SAP          |       66 | [SAP](https://finance.yahoo.com/quote/SAP/financials)                   |
|   36 |        38 | IBM          |       63 | [IBM](https://finance.yahoo.com/quote/IBM/financials)                   |
|   37 |        37 | MC           |       63 | [MC](https://finance.yahoo.com/quote/MC/financials)                     |
|   38 |        42 | PEP          |       58 | [PEP](https://finance.yahoo.com/quote/PEP/financials)                   |
|   39 |        41 | ADBE         |       58 | [ADBE](https://finance.yahoo.com/quote/ADBE/financials)                 |
|   40 |        44 | AZN          |       57 | [AZN](https://finance.yahoo.com/quote/AZN/financials)                   |
|   41 |        46 | QCOM         |       55 | [QCOM](https://finance.yahoo.com/quote/QCOM/financials)                 |
|   42 |        47 | MPC          |       53 | [MPC](https://finance.yahoo.com/quote/MPC/financials)                   |
|   43 |        50 | VLO          |       49 | [VLO](https://finance.yahoo.com/quote/VLO/financials)                   |
|   44 |        48 | BAC          |       49 | [BAC](https://finance.yahoo.com/quote/BAC/financials)                   |
|   45 |        52 | BHP          |       47 | [BHP](https://finance.yahoo.com/quote/BHP/financials)                   |
|   46 |        51 | SU           |       47 | [SU](https://finance.yahoo.com/quote/SU/financials)                     |
|   47 |        57 | HSBA         |       46 | [HSBA](https://finance.yahoo.com/quote/HSBA/financials)                 |
|   48 |        56 | ORCL         |       46 | [ORCL](https://finance.yahoo.com/quote/ORCL/financials)                 |
|   49 |        55 | KO           |       46 | [KO](https://finance.yahoo.com/quote/KO/financials)                     |
|   50 |        54 | VZ           |       46 | [VZ](https://finance.yahoo.com/quote/VZ/financials)                     |
|   51 |        59 | WFC          |       45 | [WFC](https://finance.yahoo.com/quote/WFC/financials)                   |
|   52 |        58 | WSM          |       45 | [WSM](https://finance.yahoo.com/quote/WSM/financials)                   |
|   53 |        60 | ACN          |       44 | [ACN](https://finance.yahoo.com/quote/ACN/financials)                   |
|   54 |        62 | SIE          |       42 | [SIE](https://finance.yahoo.com/quote/SIE/financials)                   |
|   55 |        61 | VST          |       42 | [VST](https://finance.yahoo.com/quote/VST/financials)                   |
|   56 |        64 | AMAT         |       41 | [AMAT](https://finance.yahoo.com/quote/AMAT/financials)                 |
|   57 |        63 | PDD          |       41 | [PDD](https://finance.yahoo.com/quote/PDD/financials)                   |
|   58 |        65 | MO           |       40 | [MO](https://finance.yahoo.com/quote/MO/financials)                     |
|   59 |        66 | SMCI         |       39 | [SMCI](https://finance.yahoo.com/quote/SMCI/financials)                 |
|   60 |        70 | UBER         |       38 | [UBER](https://finance.yahoo.com/quote/UBER/financials)                 |
|   61 |        69 | CRWD         |       38 | [CRWD](https://finance.yahoo.com/quote/CRWD/financials)                 |
|   62 |        68 | INTC         |       38 | [INTC](https://finance.yahoo.com/quote/INTC/financials)                 |
|   63 |        67 | SAN          |       38 | [SAN](https://finance.yahoo.com/quote/SAN/financials)                   |
|   64 |        74 | C            |       36 | [C](https://finance.yahoo.com/quote/C/financials)                       |
|   65 |        73 | MSTR         |       36 | [MSTR](https://finance.yahoo.com/quote/MSTR/financials)                 |
|   66 |        72 | AGPXX        |       36 | [AGPXX](https://finance.yahoo.com/quote/AGPXX/financials)               |
|   67 |        71 | ULVR         |       36 | [ULVR](https://finance.yahoo.com/quote/ULVR/financials)                 |
|   68 |        79 | PSX          |       35 | [PSX](https://finance.yahoo.com/quote/PSX/financials)                   |
|   69 |        78 | CAT          |       35 | [CAT](https://finance.yahoo.com/quote/CAT/financials)                   |
|   70 |        80 | OKE          |       34 | [OKE](https://finance.yahoo.com/quote/OKE/financials)                   |
|   71 |        82 | LIN          |       33 | [LIN](https://finance.yahoo.com/quote/LIN/financials)                   |
|   72 |        88 | EME          |       32 | [EME](https://finance.yahoo.com/quote/EME/financials)                   |
|   73 |        87 | ANET         |       32 | [ANET](https://finance.yahoo.com/quote/ANET/financials)                 |
|   74 |        86 | ALV          |       32 | [ALV](https://finance.yahoo.com/quote/ALV/financials)                   |
|   75 |        85 | MCD          |       32 | [MCD](https://finance.yahoo.com/quote/MCD/financials)                   |
|   76 |        84 | PFE          |       32 | [PFE](https://finance.yahoo.com/quote/PFE/financials)                   |
|   77 |        83 | CSL          |       32 | [CSL](https://finance.yahoo.com/quote/CSL/financials)                   |
|   78 |       100 | FANG         |       31 | [FANG](https://finance.yahoo.com/quote/FANG/financials)                 |
|   79 |        99 | NOW          |       31 | [NOW](https://finance.yahoo.com/quote/NOW/financials)                   |
|   80 |        98 | PLD          |       31 | [PLD](https://finance.yahoo.com/quote/PLD/financials)                   |
|   81 |        97 | BLDR         |       31 | [BLDR](https://finance.yahoo.com/quote/BLDR/financials)                 |
|   82 |        96 | T            |       31 | [T](https://finance.yahoo.com/quote/T/financials)                       |
|   83 |        95 | RS           |       31 | [RS](https://finance.yahoo.com/quote/RS/financials)                     |
|   84 |        94 | DIS          |       31 | [DIS](https://finance.yahoo.com/quote/DIS/financials)                   |
|   85 |        93 | COP          |       31 | [COP](https://finance.yahoo.com/quote/COP/financials)                   |
|   86 |        92 | BKNG         |       31 | [BKNG](https://finance.yahoo.com/quote/BKNG/financials)                 |
|   87 |        90 | FIX          |       31 | [FIX](https://finance.yahoo.com/quote/FIX/financials)                   |
|   88 |       107 | EOG          |       30 | [EOG](https://finance.yahoo.com/quote/EOG/financials)                   |
|   89 |       106 | AMGN         |       30 | [AMGN](https://finance.yahoo.com/quote/AMGN/financials)                 |
|   90 |       105 | NUE          |       30 | [NUE](https://finance.yahoo.com/quote/NUE/financials)                   |
|   91 |       104 | GE           |       30 | [GE](https://finance.yahoo.com/quote/GE/financials)                     |
|   92 |       103 | CMCSA        |       30 | [CMCSA](https://finance.yahoo.com/quote/CMCSA/financials)               |
|   93 |       102 | PCAR         |       30 | [PCAR](https://finance.yahoo.com/quote/PCAR/financials)                 |
|   94 |       101 | STLAM        |       30 | [STLAM](https://finance.yahoo.com/quote/STLAM/financials)               |
|   95 |       111 | FGXXX        |       29 | [FGXXX](https://finance.yahoo.com/quote/FGXXX/financials)               |
|   96 |       110 | LRCX         |       29 | [LRCX](https://finance.yahoo.com/quote/LRCX/financials)                 |
|   97 |       109 | CEG          |       29 | [CEG](https://finance.yahoo.com/quote/CEG/financials)                   |
|   98 |       117 | KLAC         |       28 | [KLAC](https://finance.yahoo.com/quote/KLAC/financials)                 |
|   99 |       116 | TSM          |       28 | [TSM](https://finance.yahoo.com/quote/TSM/financials)                   |
|  100 |       115 | ANF          |       28 | [ANF](https://finance.yahoo.com/quote/ANF/financials)                   |
|  101 |       113 | WELL         |       28 | [WELL](https://finance.yahoo.com/quote/WELL/financials)                 |
|  102 |       112 | WMB          |       28 | [WMB](https://finance.yahoo.com/quote/WMB/financials)                   |
|  103 |       123 | NEE          |       27 | [NEE](https://finance.yahoo.com/quote/NEE/financials)                   |
|  104 |       122 | SPG          |       27 | [SPG](https://finance.yahoo.com/quote/SPG/financials)                   |
|  105 |       121 | CMG          |       27 | [CMG](https://finance.yahoo.com/quote/CMG/financials)                   |
|  106 |       120 | TXN          |       27 | [TXN](https://finance.yahoo.com/quote/TXN/financials)                   |
|  107 |       119 | LOW          |       27 | [LOW](https://finance.yahoo.com/quote/LOW/financials)                   |
|  108 |       129 | WM           |       26 | [WM](https://finance.yahoo.com/quote/WM/financials)                     |
|  109 |       128 | EQIX         |       26 | [EQIX](https://finance.yahoo.com/quote/EQIX/financials)                 |
|  110 |       127 | COIN         |       26 | [COIN](https://finance.yahoo.com/quote/COIN/financials)                 |
|  111 |       126 | MU           |       26 | [MU](https://finance.yahoo.com/quote/MU/financials)                     |
|  112 |       125 | GS           |       26 | [GS](https://finance.yahoo.com/quote/GS/financials)                     |
|  113 |       142 | OR           |       25 | [OR](https://finance.yahoo.com/quote/OR/financials)                     |
|  114 |       141 | DLR          |       25 | [DLR](https://finance.yahoo.com/quote/DLR/financials)                   |
|  115 |       140 | GVMXX        |       25 | [GVMXX](https://finance.yahoo.com/quote/GVMXX/financials)               |
|  116 |       139 | DKNG         |       25 | [DKNG](https://finance.yahoo.com/quote/DKNG/financials)                 |
|  117 |       138 | DTE          |       25 | [DTE](https://finance.yahoo.com/quote/DTE/financials)                   |
|  118 |       137 | ABT          |       25 | [ABT](https://finance.yahoo.com/quote/ABT/financials)                   |
|  119 |       136 | ENB          |       25 | [ENB](https://finance.yahoo.com/quote/ENB/financials)                   |
|  120 |       135 | AXP          |       25 | [AXP](https://finance.yahoo.com/quote/AXP/financials)                   |
|  121 |       134 | OC           |       25 | [OC](https://finance.yahoo.com/quote/OC/financials)                     |
|  122 |       133 | PXD          |       25 | [PXD](https://finance.yahoo.com/quote/PXD/financials)                   |
|  123 |       132 | BMY          |       25 | [BMY](https://finance.yahoo.com/quote/BMY/financials)                   |
|  124 |       131 | MANH         |       25 | [MANH](https://finance.yahoo.com/quote/MANH/financials)                 |
|  125 |       130 | MBG          |       25 | [MBG](https://finance.yahoo.com/quote/MBG/financials)                   |
|  126 |       157 | INTU         |       24 | [INTU](https://finance.yahoo.com/quote/INTU/financials)                 |
|  127 |       156 | BCC          |       24 | [BCC](https://finance.yahoo.com/quote/BCC/financials)                   |
|  128 |       155 | BP           |       24 | [BP](https://finance.yahoo.com/quote/BP/financials)                     |
|  129 |       154 | VALE3        |       24 | [VALE3](https://finance.yahoo.com/quote/VALE3/financials)               |
|  130 |       153 | KMI          |       24 | [KMI](https://finance.yahoo.com/quote/KMI/financials)                   |
|  131 |       152 | MMM          |       24 | [MMM](https://finance.yahoo.com/quote/MMM/financials)                   |
|  132 |       151 | ROP          |       24 | [ROP](https://finance.yahoo.com/quote/ROP/financials)                   |
|  133 |       150 | LNG          |       24 | [LNG](https://finance.yahoo.com/quote/LNG/financials)                   |
|  134 |       149 | PGR          |       24 | [PGR](https://finance.yahoo.com/quote/PGR/financials)                   |
|  135 |       148 | SNPS         |       24 | [SNPS](https://finance.yahoo.com/quote/SNPS/financials)                 |
|  136 |       147 | FXFXX        |       24 | [FXFXX](https://finance.yahoo.com/quote/FXFXX/financials)               |
|  137 |       146 | BA           |       24 | [BA](https://finance.yahoo.com/quote/BA/financials)                     |
|  138 |       145 | DKS          |       24 | [DKS](https://finance.yahoo.com/quote/DKS/financials)                   |
|  139 |       143 | PSA          |       24 | [PSA](https://finance.yahoo.com/quote/PSA/financials)                   |
|  140 |       164 | LMT          |       23 | [LMT](https://finance.yahoo.com/quote/LMT/financials)                   |
|  141 |       163 | ETN          |       23 | [ETN](https://finance.yahoo.com/quote/ETN/financials)                   |
|  142 |       162 | AVB          |       23 | [AVB](https://finance.yahoo.com/quote/AVB/financials)                   |
|  143 |       161 | PM           |       23 | [PM](https://finance.yahoo.com/quote/PM/financials)                     |
|  144 |       160 | DASH         |       23 | [DASH](https://finance.yahoo.com/quote/DASH/financials)                 |
|  145 |       159 | APH          |       23 | [APH](https://finance.yahoo.com/quote/APH/financials)                   |
|  146 |       158 | REGN         |       23 | [REGN](https://finance.yahoo.com/quote/REGN/financials)                 |
|  147 |       181 | RSG          |       22 | [RSG](https://finance.yahoo.com/quote/RSG/financials)                   |
|  148 |       180 | TMUS         |       22 | [TMUS](https://finance.yahoo.com/quote/TMUS/financials)                 |
|  149 |       179 | DOW          |       22 | [DOW](https://finance.yahoo.com/quote/DOW/financials)                   |
|  150 |       178 | LYB          |       22 | [LYB](https://finance.yahoo.com/quote/LYB/financials)                   |
|  151 |       177 | CDNS         |       22 | [CDNS](https://finance.yahoo.com/quote/CDNS/financials)                 |
|  152 |       176 | SAIA         |       22 | [SAIA](https://finance.yahoo.com/quote/SAIA/financials)                 |
|  153 |       175 | STLD         |       22 | [STLD](https://finance.yahoo.com/quote/STLD/financials)                 |
|  154 |       174 | RIO          |       22 | [RIO](https://finance.yahoo.com/quote/RIO/financials)                   |
|  155 |       173 | RY           |       22 | [RY](https://finance.yahoo.com/quote/RY/financials)                     |
|  156 |       172 | ELF          |       22 | [ELF](https://finance.yahoo.com/quote/ELF/financials)                   |
|  157 |       171 | GSK          |       22 | [GSK](https://finance.yahoo.com/quote/GSK/financials)                   |
|  158 |       170 | NXPI         |       22 | [NXPI](https://finance.yahoo.com/quote/NXPI/financials)                 |
|  159 |       169 | TMO          |       22 | [TMO](https://finance.yahoo.com/quote/TMO/financials)                   |
|  160 |       167 | FCX          |       22 | [FCX](https://finance.yahoo.com/quote/FCX/financials)                   |
|  161 |       166 | ISRG         |       22 | [ISRG](https://finance.yahoo.com/quote/ISRG/financials)                 |
|  162 |       165 | ECL          |       22 | [ECL](https://finance.yahoo.com/quote/ECL/financials)                   |
|  163 |       191 | DHR          |       21 | [DHR](https://finance.yahoo.com/quote/DHR/financials)                   |
|  164 |       190 | DECK         |       21 | [DECK](https://finance.yahoo.com/quote/DECK/financials)                 |
|  165 |       189 | VRT          |       21 | [VRT](https://finance.yahoo.com/quote/VRT/financials)                   |
|  166 |       188 | IBP          |       21 | [IBP](https://finance.yahoo.com/quote/IBP/financials)                   |
|  167 |       186 | TOL          |       21 | [TOL](https://finance.yahoo.com/quote/TOL/financials)                   |
|  168 |       185 | DE           |       21 | [DE](https://finance.yahoo.com/quote/DE/financials)                     |
|  169 |       184 | EPD          |       21 | [EPD](https://finance.yahoo.com/quote/EPD/financials)                   |
|  170 |       183 | SO           |       21 | [SO](https://finance.yahoo.com/quote/SO/financials)                     |
|  171 |       182 | COR          |       21 | [COR](https://finance.yahoo.com/quote/COR/financials)                   |
|  172 |       206 | UPS          |       20 | [UPS](https://finance.yahoo.com/quote/UPS/financials)                   |
|  173 |       205 | ZURN         |       20 | [ZURN](https://finance.yahoo.com/quote/ZURN/financials)                 |
|  174 |       204 | GGG          |       20 | [GGG](https://finance.yahoo.com/quote/GGG/financials)                   |
|  175 |       203 | MCK          |       20 | [MCK](https://finance.yahoo.com/quote/MCK/financials)                   |
|  176 |       202 | EXR          |       20 | [EXR](https://finance.yahoo.com/quote/EXR/financials)                   |
|  177 |       201 | PHM          |       20 | [PHM](https://finance.yahoo.com/quote/PHM/financials)                   |
|  178 |       200 | TRGP         |       20 | [TRGP](https://finance.yahoo.com/quote/TRGP/financials)                 |
|  179 |       199 | MELI         |       20 | [MELI](https://finance.yahoo.com/quote/MELI/financials)                 |
|  180 |       198 | SQ           |       20 | [SQ](https://finance.yahoo.com/quote/SQ/financials)                     |
|  181 |       197 | GD           |       20 | [GD](https://finance.yahoo.com/quote/GD/financials)                     |
|  182 |       196 | O            |       20 | [O](https://finance.yahoo.com/quote/O/financials)                       |
|  183 |       195 | MS           |       20 | [MS](https://finance.yahoo.com/quote/MS/financials)                     |
|  184 |       194 | VICI         |       20 | [VICI](https://finance.yahoo.com/quote/VICI/financials)                 |
|  185 |       193 | BABA         |       20 | [BABA](https://finance.yahoo.com/quote/BABA/financials)                 |
|  186 |       192 | ADM          |       20 | [ADM](https://finance.yahoo.com/quote/ADM/financials)                   |
|  187 |       220 | MTH          |       19 | [MTH](https://finance.yahoo.com/quote/MTH/financials)                   |
|  188 |       219 | CTVA         |       19 | [CTVA](https://finance.yahoo.com/quote/CTVA/financials)                 |
|  189 |       218 | SM           |       19 | [SM](https://finance.yahoo.com/quote/SM/financials)                     |
|  190 |       217 | ET           |       19 | [ET](https://finance.yahoo.com/quote/ET/financials)                     |
|  191 |       216 | CVS          |       19 | [CVS](https://finance.yahoo.com/quote/CVS/financials)                   |
|  192 |       215 | FN           |       19 | [FN](https://finance.yahoo.com/quote/FN/financials)                     |
|  193 |       214 | CL           |       19 | [CL](https://finance.yahoo.com/quote/CL/financials)                     |
|  194 |       213 | MSI          |       19 | [MSI](https://finance.yahoo.com/quote/MSI/financials)                   |
|  195 |       211 | RTX          |       19 | [RTX](https://finance.yahoo.com/quote/RTX/financials)                   |
|  196 |       210 | ENPH         |       19 | [ENPH](https://finance.yahoo.com/quote/ENPH/financials)                 |
|  197 |       209 | PSTG         |       19 | [PSTG](https://finance.yahoo.com/quote/PSTG/financials)                 |
|  198 |       208 | CPRT         |       19 | [CPRT](https://finance.yahoo.com/quote/CPRT/financials)                 |
|  199 |       230 | ENSG         |       18 | [ENSG](https://finance.yahoo.com/quote/ENSG/financials)                 |
|  200 |       229 | GILD         |       18 | [GILD](https://finance.yahoo.com/quote/GILD/financials)                 |
|  201 |       228 | UNP          |       18 | [UNP](https://finance.yahoo.com/quote/UNP/financials)                   |
|  202 |       226 | MLI          |       18 | [MLI](https://finance.yahoo.com/quote/MLI/financials)                   |
|  203 |       225 | TJX          |       18 | [TJX](https://finance.yahoo.com/quote/TJX/financials)                   |
|  204 |       224 | PR           |       18 | [PR](https://finance.yahoo.com/quote/PR/financials)                     |
|  205 |       223 | LII          |       18 | [LII](https://finance.yahoo.com/quote/LII/financials)                   |
|  206 |       222 | GDDY         |       18 | [GDDY](https://finance.yahoo.com/quote/GDDY/financials)                 |
|  207 |       221 | ABNB         |       18 | [ABNB](https://finance.yahoo.com/quote/ABNB/financials)                 |
|  208 |       248 | VRTX         |       17 | [VRTX](https://finance.yahoo.com/quote/VRTX/financials)                 |
|  209 |       247 | ORLY         |       17 | [ORLY](https://finance.yahoo.com/quote/ORLY/financials)                 |
|  210 |       246 | AXON         |       17 | [AXON](https://finance.yahoo.com/quote/AXON/financials)                 |
|  211 |       245 | PYPL         |       17 | [PYPL](https://finance.yahoo.com/quote/PYPL/financials)                 |
|  212 |       244 | CF           |       17 | [CF](https://finance.yahoo.com/quote/CF/financials)                     |
|  213 |       243 | MAR          |       17 | [MAR](https://finance.yahoo.com/quote/MAR/financials)                   |
|  214 |       242 | WES          |       17 | [WES](https://finance.yahoo.com/quote/WES/financials)                   |
|  215 |       241 | TT           |       17 | [TT](https://finance.yahoo.com/quote/TT/financials)                     |
|  216 |       240 | FSLR         |       17 | [FSLR](https://finance.yahoo.com/quote/FSLR/financials)                 |
|  217 |       239 | SRE          |       17 | [SRE](https://finance.yahoo.com/quote/SRE/financials)                   |
|  218 |       238 | EQR          |       17 | [EQR](https://finance.yahoo.com/quote/EQR/financials)                   |
|  219 |       237 | SPSC         |       17 | [SPSC](https://finance.yahoo.com/quote/SPSC/financials)                 |
|  220 |       236 | DUK          |       17 | [DUK](https://finance.yahoo.com/quote/DUK/financials)                   |
|  221 |       235 | X            |       17 | [X](https://finance.yahoo.com/quote/X/financials)                       |
|  222 |       234 | PBF          |       17 | [PBF](https://finance.yahoo.com/quote/PBF/financials)                   |
|  223 |       231 | ITX          |       17 | [ITX](https://finance.yahoo.com/quote/ITX/financials)                   |
|  224 |       264 | APP          |       16 | [APP](https://finance.yahoo.com/quote/APP/financials)                   |
|  225 |       263 | ORA          |       16 | [ORA](https://finance.yahoo.com/quote/ORA/financials)                   |
|  226 |       261 | MPLX         |       16 | [MPLX](https://finance.yahoo.com/quote/MPLX/financials)                 |
|  227 |       260 | CI           |       16 | [CI](https://finance.yahoo.com/quote/CI/financials)                     |
|  228 |       259 | TDG          |       16 | [TDG](https://finance.yahoo.com/quote/TDG/financials)                   |
|  229 |       258 | KR           |       16 | [KR](https://finance.yahoo.com/quote/KR/financials)                     |
|  230 |       256 | UBSG         |       16 | [UBSG](https://finance.yahoo.com/quote/UBSG/financials)                 |
|  231 |       254 | WFRD         |       16 | [WFRD](https://finance.yahoo.com/quote/WFRD/financials)                 |
|  232 |       253 | WDAY         |       16 | [WDAY](https://finance.yahoo.com/quote/WDAY/financials)                 |
|  233 |       252 | HON          |       16 | [HON](https://finance.yahoo.com/quote/HON/financials)                   |
|  234 |       251 | CNQ          |       16 | [CNQ](https://finance.yahoo.com/quote/CNQ/financials)                   |
|  235 |       250 | MTG          |       16 | [MTG](https://finance.yahoo.com/quote/MTG/financials)                   |
|  236 |       249 | IBE          |       16 | [IBE](https://finance.yahoo.com/quote/IBE/financials)                   |
|  237 |       287 | LECO         |       15 | [LECO](https://finance.yahoo.com/quote/LECO/financials)                 |
|  238 |       286 | CCI          |       15 | [CCI](https://finance.yahoo.com/quote/CCI/financials)                   |
|  239 |       285 | KEY          |       15 | [KEY](https://finance.yahoo.com/quote/KEY/financials)                   |
|  240 |       284 | TGT          |       15 | [TGT](https://finance.yahoo.com/quote/TGT/financials)                   |
|  241 |       283 | GLEN         |       15 | [GLEN](https://finance.yahoo.com/quote/GLEN/financials)                 |
|  242 |       282 | FAST         |       15 | [FAST](https://finance.yahoo.com/quote/FAST/financials)                 |
|  243 |       281 | KMB          |       15 | [KMB](https://finance.yahoo.com/quote/KMB/financials)                   |
|  244 |       280 | SYK          |       15 | [SYK](https://finance.yahoo.com/quote/SYK/financials)                   |
|  245 |       279 | RDN          |       15 | [RDN](https://finance.yahoo.com/quote/RDN/financials)                   |
|  246 |       278 | PETR4        |       15 | [PETR4](https://finance.yahoo.com/quote/PETR4/financials)               |
|  247 |       277 | IP           |       15 | [IP](https://finance.yahoo.com/quote/IP/financials)                     |
|  248 |       276 | PANW         |       15 | [PANW](https://finance.yahoo.com/quote/PANW/financials)                 |
|  249 |       275 | NEM          |       15 | [NEM](https://finance.yahoo.com/quote/NEM/financials)                   |
|  250 |       274 | PWR          |       15 | [PWR](https://finance.yahoo.com/quote/PWR/financials)                   |
|  251 |       273 | BBCA         |       15 | [BBCA](https://finance.yahoo.com/quote/BBCA/financials)                 |
|  252 |       272 | GWW          |       15 | [GWW](https://finance.yahoo.com/quote/GWW/financials)                   |
|  253 |       271 | MDT          |       15 | [MDT](https://finance.yahoo.com/quote/MDT/financials)                   |
|  254 |       270 | MRO          |       15 | [MRO](https://finance.yahoo.com/quote/MRO/financials)                   |
|  255 |       269 | CAH          |       15 | [CAH](https://finance.yahoo.com/quote/CAH/financials)                   |
|  256 |       268 | TRV          |       15 | [TRV](https://finance.yahoo.com/quote/TRV/financials)                   |
|  257 |       267 | CNM          |       15 | [CNM](https://finance.yahoo.com/quote/CNM/financials)                   |
|  258 |       266 | NBIX         |       15 | [NBIX](https://finance.yahoo.com/quote/NBIX/financials)                 |
|  259 |       319 | HOOD         |       14 | [HOOD](https://finance.yahoo.com/quote/HOOD/financials)                 |
|  260 |       318 | ADI          |       14 | [ADI](https://finance.yahoo.com/quote/ADI/financials)                   |
|  261 |       317 | CVNA         |       14 | [CVNA](https://finance.yahoo.com/quote/CVNA/financials)                 |
|  262 |       315 | PRU          |       14 | [PRU](https://finance.yahoo.com/quote/PRU/financials)                   |
|  263 |       314 | GIS          |       14 | [GIS](https://finance.yahoo.com/quote/GIS/financials)                   |
|  264 |       313 | JXN          |       14 | [JXN](https://finance.yahoo.com/quote/JXN/financials)                   |
|  265 |       312 | SCHW         |       14 | [SCHW](https://finance.yahoo.com/quote/SCHW/financials)                 |
|  266 |       311 | COF          |       14 | [COF](https://finance.yahoo.com/quote/COF/financials)                   |
|  267 |       310 | ADP          |       14 | [ADP](https://finance.yahoo.com/quote/ADP/financials)                   |
|  268 |       309 | AIG          |       14 | [AIG](https://finance.yahoo.com/quote/AIG/financials)                   |
|  269 |       308 | AMT          |       14 | [AMT](https://finance.yahoo.com/quote/AMT/financials)                   |
|  270 |       307 | AIT          |       14 | [AIT](https://finance.yahoo.com/quote/AIT/financials)                   |
|  271 |       306 | RMS          |       14 | [RMS](https://finance.yahoo.com/quote/RMS/financials)                   |
|  272 |       303 | BG           |       14 | [BG](https://finance.yahoo.com/quote/BG/financials)                     |
|  273 |       302 | NXT          |       14 | [NXT](https://finance.yahoo.com/quote/NXT/financials)                   |
|  274 |       301 | MRVL         |       14 | [MRVL](https://finance.yahoo.com/quote/MRVL/financials)                 |
|  275 |       300 | SPXC         |       14 | [SPXC](https://finance.yahoo.com/quote/SPXC/financials)                 |
|  276 |       299 | GRMN         |       14 | [GRMN](https://finance.yahoo.com/quote/GRMN/financials)                 |
|  277 |       298 | AMR          |       14 | [AMR](https://finance.yahoo.com/quote/AMR/financials)                   |
|  278 |       297 | LEN          |       14 | [LEN](https://finance.yahoo.com/quote/LEN/financials)                   |
|  279 |       296 | CBA          |       14 | [CBA](https://finance.yahoo.com/quote/CBA/financials)                   |
|  280 |       295 | GM           |       14 | [GM](https://finance.yahoo.com/quote/GM/financials)                     |
|  281 |       294 | MMC          |       14 | [MMC](https://finance.yahoo.com/quote/MMC/financials)                   |
|  282 |       293 | URI          |       14 | [URI](https://finance.yahoo.com/quote/URI/financials)                   |
|  283 |       292 | ONTO         |       14 | [ONTO](https://finance.yahoo.com/quote/ONTO/financials)                 |
|  284 |       291 | NG           |       14 | [NG](https://finance.yahoo.com/quote/NG/financials)                     |
|  285 |       290 | TTWO         |       14 | [TTWO](https://finance.yahoo.com/quote/TTWO/financials)                 |
|  286 |       289 | ELV          |       14 | [ELV](https://finance.yahoo.com/quote/ELV/financials)                   |
|  287 |       288 | PAA          |       14 | [PAA](https://finance.yahoo.com/quote/PAA/financials)                   |
|  288 |       354 | PCG          |       13 | [PCG](https://finance.yahoo.com/quote/PCG/financials)                   |
|  289 |       353 | ATI          |       13 | [ATI](https://finance.yahoo.com/quote/ATI/financials)                   |
|  290 |       352 | DHI          |       13 | [DHI](https://finance.yahoo.com/quote/DHI/financials)                   |
|  291 |       351 | F            |       13 | [F](https://finance.yahoo.com/quote/F/financials)                       |
|  292 |       350 | RCL          |       13 | [RCL](https://finance.yahoo.com/quote/RCL/financials)                   |
|  293 |       349 | BATS         |       13 | [BATS](https://finance.yahoo.com/quote/BATS/financials)                 |
|  294 |       348 | DXCM         |       13 | [DXCM](https://finance.yahoo.com/quote/DXCM/financials)                 |
|  295 |       347 | RPM          |       13 | [RPM](https://finance.yahoo.com/quote/RPM/financials)                   |
|  296 |       346 | EBAY         |       13 | [EBAY](https://finance.yahoo.com/quote/EBAY/financials)                 |
|  297 |       345 | CB           |       13 | [CB](https://finance.yahoo.com/quote/CB/financials)                     |
|  298 |       344 | OXY          |       13 | [OXY](https://finance.yahoo.com/quote/OXY/financials)                   |
|  299 |       343 | AWI          |       13 | [AWI](https://finance.yahoo.com/quote/AWI/financials)                   |
|  300 |       342 | SPGI         |       13 | [SPGI](https://finance.yahoo.com/quote/SPGI/financials)                 |
|  301 |       341 | ANSS         |       13 | [ANSS](https://finance.yahoo.com/quote/ANSS/financials)                 |
|  302 |       340 | PPL          |       13 | [PPL](https://finance.yahoo.com/quote/PPL/financials)                   |
|  303 |       339 | PTC          |       13 | [PTC](https://finance.yahoo.com/quote/PTC/financials)                   |
|  304 |       338 | INVH         |       13 | [INVH](https://finance.yahoo.com/quote/INVH/financials)                 |
|  305 |       337 | THC          |       13 | [THC](https://finance.yahoo.com/quote/THC/financials)                   |
|  306 |       336 | PLTR         |       13 | [PLTR](https://finance.yahoo.com/quote/PLTR/financials)                 |
|  307 |       335 | CTAS         |       13 | [CTAS](https://finance.yahoo.com/quote/CTAS/financials)                 |
|  308 |       334 | EIX          |       13 | [EIX](https://finance.yahoo.com/quote/EIX/financials)                   |
|  309 |       333 | NKE          |       13 | [NKE](https://finance.yahoo.com/quote/NKE/financials)                   |
|  310 |       332 | HES          |       13 | [HES](https://finance.yahoo.com/quote/HES/financials)                   |
|  311 |       331 | EMR          |       13 | [EMR](https://finance.yahoo.com/quote/EMR/financials)                   |
|  312 |       330 | AFL          |       13 | [AFL](https://finance.yahoo.com/quote/AFL/financials)                   |
|  313 |       329 | SYY          |       13 | [SYY](https://finance.yahoo.com/quote/SYY/financials)                   |
|  314 |       328 | HUBB         |       13 | [HUBB](https://finance.yahoo.com/quote/HUBB/financials)                 |
|  315 |       327 | APD          |       13 | [APD](https://finance.yahoo.com/quote/APD/financials)                   |
|  316 |       323 | SHW          |       13 | [SHW](https://finance.yahoo.com/quote/SHW/financials)                   |
|  317 |       322 | AWK          |       13 | [AWK](https://finance.yahoo.com/quote/AWK/financials)                   |
|  318 |       321 | NET          |       13 | [NET](https://finance.yahoo.com/quote/NET/financials)                   |
|  319 |       320 | PEG          |       13 | [PEG](https://finance.yahoo.com/quote/PEG/financials)                   |
|  320 |       388 | TD           |       12 | [TD](https://finance.yahoo.com/quote/TD/financials)                     |
|  321 |       387 | ED           |       12 | [ED](https://finance.yahoo.com/quote/ED/financials)                     |
|  322 |       386 | NTRA         |       12 | [NTRA](https://finance.yahoo.com/quote/NTRA/financials)                 |
|  323 |       385 | ADSK         |       12 | [ADSK](https://finance.yahoo.com/quote/ADSK/financials)                 |
|  324 |       383 | INFY         |       12 | [INFY](https://finance.yahoo.com/quote/INFY/financials)                 |
|  325 |       382 | SHOP         |       12 | [SHOP](https://finance.yahoo.com/quote/SHOP/financials)                 |
|  326 |       381 | D05          |       12 | [D05](https://finance.yahoo.com/quote/D05/financials)                   |
|  327 |       380 | AAON         |       12 | [AAON](https://finance.yahoo.com/quote/AAON/financials)                 |
|  328 |       379 | REL          |       12 | [REL](https://finance.yahoo.com/quote/REL/financials)                   |
|  329 |       378 | LDOS         |       12 | [LDOS](https://finance.yahoo.com/quote/LDOS/financials)                 |
|  330 |       377 | EA           |       12 | [EA](https://finance.yahoo.com/quote/EA/financials)                     |
|  331 |       376 | TMHC         |       12 | [TMHC](https://finance.yahoo.com/quote/TMHC/financials)                 |
|  332 |       375 | ENEL         |       12 | [ENEL](https://finance.yahoo.com/quote/ENEL/financials)                 |
|  333 |       372 | BRBR         |       12 | [BRBR](https://finance.yahoo.com/quote/BRBR/financials)                 |
|  334 |       371 | CSX          |       12 | [CSX](https://finance.yahoo.com/quote/CSX/financials)                   |
|  335 |       370 | JNPR         |       12 | [JNPR](https://finance.yahoo.com/quote/JNPR/financials)                 |
|  336 |       369 | BIDU         |       12 | [BIDU](https://finance.yahoo.com/quote/BIDU/financials)                 |
|  337 |       368 | WY           |       12 | [WY](https://finance.yahoo.com/quote/WY/financials)                     |
|  338 |       367 | FB           |       12 | [FB](https://finance.yahoo.com/quote/FB/financials)                     |
|  339 |       366 | USB          |       12 | [USB](https://finance.yahoo.com/quote/USB/financials)                   |
|  340 |       365 | XYL          |       12 | [XYL](https://finance.yahoo.com/quote/XYL/financials)                   |
|  341 |       364 | IVV          |       12 | [IVV](https://finance.yahoo.com/quote/IVV/financials)                   |
|  342 |       363 | AZO          |       12 | [AZO](https://finance.yahoo.com/quote/AZO/financials)                   |
|  343 |       362 | XLF          |       12 | [XLF](https://finance.yahoo.com/quote/XLF/financials)                   |
|  344 |       361 | CSGP         |       12 | [CSGP](https://finance.yahoo.com/quote/CSGP/financials)                 |
|  345 |       360 | BMW          |       12 | [BMW](https://finance.yahoo.com/quote/BMW/financials)                   |
|  346 |       358 | SLB          |       12 | [SLB](https://finance.yahoo.com/quote/SLB/financials)                   |
|  347 |       357 | BLD          |       12 | [BLD](https://finance.yahoo.com/quote/BLD/financials)                   |
|  348 |       355 | LULU         |       12 | [LULU](https://finance.yahoo.com/quote/LULU/financials)                 |
|  349 |       433 | GMG          |       11 | [GMG](https://finance.yahoo.com/quote/GMG/financials)                   |
|  350 |       432 | DELL         |       11 | [DELL](https://finance.yahoo.com/quote/DELL/financials)                 |
|  351 |       431 | ATKR         |       11 | [ATKR](https://finance.yahoo.com/quote/ATKR/financials)                 |
|  352 |       430 | ALL          |       11 | [ALL](https://finance.yahoo.com/quote/ALL/financials)                   |
|  353 |       429 | UNM          |       11 | [UNM](https://finance.yahoo.com/quote/UNM/financials)                   |
|  354 |       428 | CHKP         |       11 | [CHKP](https://finance.yahoo.com/quote/CHKP/financials)                 |
|  355 |       427 | OKTA         |       11 | [OKTA](https://finance.yahoo.com/quote/OKTA/financials)                 |
|  356 |       426 | CLSK         |       11 | [CLSK](https://finance.yahoo.com/quote/CLSK/financials)                 |
|  357 |       425 | TSCO         |       11 | [TSCO](https://finance.yahoo.com/quote/TSCO/financials)                 |
|  358 |       424 | TRP          |       11 | [TRP](https://finance.yahoo.com/quote/TRP/financials)                   |
|  359 |       423 | MDLZ         |       11 | [MDLZ](https://finance.yahoo.com/quote/MDLZ/financials)                 |
|  360 |       422 | KBH          |       11 | [KBH](https://finance.yahoo.com/quote/KBH/financials)                   |
|  361 |       421 | DVN          |       11 | [DVN](https://finance.yahoo.com/quote/DVN/financials)                   |
|  362 |       420 | ARE          |       11 | [ARE](https://finance.yahoo.com/quote/ARE/financials)                   |
|  363 |       419 | DG           |       11 | [DG](https://finance.yahoo.com/quote/DG/financials)                     |
|  364 |       418 | NU           |       11 | [NU](https://finance.yahoo.com/quote/NU/financials)                     |
|  365 |       417 | COOP         |       11 | [COOP](https://finance.yahoo.com/quote/COOP/financials)                 |
|  366 |       416 | D            |       11 | [D](https://finance.yahoo.com/quote/D/financials)                       |
|  367 |       415 | ICE          |       11 | [ICE](https://finance.yahoo.com/quote/ICE/financials)                   |
|  368 |       414 | VTRS         |       11 | [VTRS](https://finance.yahoo.com/quote/VTRS/financials)                 |
|  369 |       413 | NTNX         |       11 | [NTNX](https://finance.yahoo.com/quote/NTNX/financials)                 |
|  370 |       412 | BBVA         |       11 | [BBVA](https://finance.yahoo.com/quote/BBVA/financials)                 |
|  371 |       411 | PATH         |       11 | [PATH](https://finance.yahoo.com/quote/PATH/financials)                 |
|  372 |       410 | OGN          |       11 | [OGN](https://finance.yahoo.com/quote/OGN/financials)                   |
|  373 |       409 | ODFL         |       11 | [ODFL](https://finance.yahoo.com/quote/ODFL/financials)                 |
|  374 |       408 | AIR          |       11 | [AIR](https://finance.yahoo.com/quote/AIR/financials)                   |
|  375 |       407 | XLK          |       11 | [XLK](https://finance.yahoo.com/quote/XLK/financials)                   |
|  376 |       406 | BAH          |       11 | [BAH](https://finance.yahoo.com/quote/BAH/financials)                   |
|  377 |       405 | USFD         |       11 | [USFD](https://finance.yahoo.com/quote/USFD/financials)                 |
|  378 |       404 | ASO          |       11 | [ASO](https://finance.yahoo.com/quote/ASO/financials)                   |
|  379 |       403 | DINO         |       11 | [DINO](https://finance.yahoo.com/quote/DINO/financials)                 |
|  380 |       402 | LNW          |       11 | [LNW](https://finance.yahoo.com/quote/LNW/financials)                   |
|  381 |       401 | CELH         |       11 | [CELH](https://finance.yahoo.com/quote/CELH/financials)                 |
|  382 |       400 | CMI          |       11 | [CMI](https://finance.yahoo.com/quote/CMI/financials)                   |
|  383 |       399 | MOD          |       11 | [MOD](https://finance.yahoo.com/quote/MOD/financials)                   |
|  384 |       398 | DAL          |       11 | [DAL](https://finance.yahoo.com/quote/DAL/financials)                   |
|  385 |       397 | DGCXX        |       11 | [DGCXX](https://finance.yahoo.com/quote/DGCXX/financials)               |
|  386 |       396 | MCHP         |       11 | [MCHP](https://finance.yahoo.com/quote/MCHP/financials)                 |
|  387 |       395 | MEDP         |       11 | [MEDP](https://finance.yahoo.com/quote/MEDP/financials)                 |
|  388 |       394 | VMC          |       11 | [VMC](https://finance.yahoo.com/quote/VMC/financials)                   |
|  389 |       392 | ABBN         |       11 | [ABBN](https://finance.yahoo.com/quote/ABBN/financials)                 |
|  390 |       391 | MDC          |       11 | [MDC](https://finance.yahoo.com/quote/MDC/financials)                   |
|  391 |       389 | UCG          |       11 | [UCG](https://finance.yahoo.com/quote/UCG/financials)                   |
|  392 |       472 | STZ          |       10 | [STZ](https://finance.yahoo.com/quote/STZ/financials)                   |
|  393 |       471 | APA          |       10 | [APA](https://finance.yahoo.com/quote/APA/financials)                   |
|  394 |       470 | TFC          |       10 | [TFC](https://finance.yahoo.com/quote/TFC/financials)                   |
|  395 |       469 | APO          |       10 | [APO](https://finance.yahoo.com/quote/APO/financials)                   |
|  396 |       468 | EXC          |       10 | [EXC](https://finance.yahoo.com/quote/EXC/financials)                   |
|  397 |       467 | WING         |       10 | [WING](https://finance.yahoo.com/quote/WING/financials)                 |
|  398 |       466 | KKR          |       10 | [KKR](https://finance.yahoo.com/quote/KKR/financials)                   |
|  399 |       465 | SSD          |       10 | [SSD](https://finance.yahoo.com/quote/SSD/financials)                   |
|  400 |       464 | RGA          |       10 | [RGA](https://finance.yahoo.com/quote/RGA/financials)                   |
|  401 |       463 | SSIXX        |       10 | [SSIXX](https://finance.yahoo.com/quote/SSIXX/financials)               |
|  402 |       462 | AJG          |       10 | [AJG](https://finance.yahoo.com/quote/AJG/financials)                   |
|  403 |       461 | IFF          |       10 | [IFF](https://finance.yahoo.com/quote/IFF/financials)                   |
|  404 |       460 | FERG         |       10 | [FERG](https://finance.yahoo.com/quote/FERG/financials)                 |
|  405 |       459 | DDOG         |       10 | [DDOG](https://finance.yahoo.com/quote/DDOG/financials)                 |
|  406 |       458 | PNR          |       10 | [PNR](https://finance.yahoo.com/quote/PNR/financials)                   |
|  407 |       457 | BLK          |       10 | [BLK](https://finance.yahoo.com/quote/BLK/financials)                   |
|  408 |       455 | XPO          |       10 | [XPO](https://finance.yahoo.com/quote/XPO/financials)                   |
|  409 |       454 | Other        |       10 | [Other](https://finance.yahoo.com/quote/Other/financials)               |
|  410 |       453 | CTRA         |       10 | [CTRA](https://finance.yahoo.com/quote/CTRA/financials)                 |
|  411 |       452 | IRM          |       10 | [IRM](https://finance.yahoo.com/quote/IRM/financials)                   |
|  412 |       451 | SRPT         |       10 | [SRPT](https://finance.yahoo.com/quote/SRPT/financials)                 |
|  413 |       450 | NTR          |       10 | [NTR](https://finance.yahoo.com/quote/NTR/financials)                   |
|  414 |       449 | NS           |       10 | [NS](https://finance.yahoo.com/quote/NS/financials)                     |
|  415 |       448 | WMS          |       10 | [WMS](https://finance.yahoo.com/quote/WMS/financials)                   |
|  416 |       447 | WIRE         |       10 | [WIRE](https://finance.yahoo.com/quote/WIRE/financials)                 |
|  417 |       446 | ZS           |       10 | [ZS](https://finance.yahoo.com/quote/ZS/financials)                     |
|  418 |       445 | FTNT         |       10 | [FTNT](https://finance.yahoo.com/quote/FTNT/financials)                 |
|  419 |       443 | HIG          |       10 | [HIG](https://finance.yahoo.com/quote/HIG/financials)                   |
|  420 |       442 | XLI          |       10 | [XLI](https://finance.yahoo.com/quote/XLI/financials)                   |
|  421 |       440 | DHL          |       10 | [DHL](https://finance.yahoo.com/quote/DHL/financials)                   |
|  422 |       439 | BAS          |       10 | [BAS](https://finance.yahoo.com/quote/BAS/financials)                   |
|  423 |       438 | MLM          |       10 | [MLM](https://finance.yahoo.com/quote/MLM/financials)                   |
|  424 |       437 | TEL          |       10 | [TEL](https://finance.yahoo.com/quote/TEL/financials)                   |
|  425 |       435 | NSC          |       10 | [NSC](https://finance.yahoo.com/quote/NSC/financials)                   |
|  426 |       434 | O39          |       10 | [O39](https://finance.yahoo.com/quote/O39/financials)                   |
|  444 |       498 | XLV          |        9 | [XLV](https://finance.yahoo.com/quote/XLV/financials)                   |
|  445 |       497 | XLC          |        9 | [XLC](https://finance.yahoo.com/quote/XLC/financials)                   |
|  472 |       583 | TSN          |        8 | [TSN](https://finance.yahoo.com/quote/TSN/financials)                   |
|  497 |       556 | SBUX         |        8 | [SBUX](https://finance.yahoo.com/quote/SBUX/financials)                 |
|  499 |       554 | A            |        8 | [A](https://finance.yahoo.com/quote/A/financials)                       |
|  511 |       542 | ROST         |        8 | [ROST](https://finance.yahoo.com/quote/ROST/financials)                 |
|  527 |       525 | QQQ          |        8 | [QQQ](https://finance.yahoo.com/quote/QQQ/financials)                   |
|  542 |       664 | XLY          |        7 | [XLY](https://finance.yahoo.com/quote/XLY/financials)                   |
|  543 |       662 | XLE          |        7 | [XLE](https://finance.yahoo.com/quote/XLE/financials)                   |
|  547 |       658 | VOO          |        7 | [VOO](https://finance.yahoo.com/quote/VOO/financials)                   |
|  549 |       656 | FICO         |        7 | [FICO](https://finance.yahoo.com/quote/FICO/financials)                 |
|  556 |       648 | JD           |        7 | [JD](https://finance.yahoo.com/quote/JD/financials)                     |
|  558 |       646 | APG          |        7 | [APG](https://finance.yahoo.com/quote/APG/financials)                   |
|  559 |       645 | BIIB         |        7 | [BIIB](https://finance.yahoo.com/quote/BIIB/financials)                 |
|  576 |       625 | PNC          |        7 | [PNC](https://finance.yahoo.com/quote/PNC/financials)                   |
|  661 |       733 | SPY          |        6 | [SPY](https://finance.yahoo.com/quote/SPY/financials)                   |
|  662 |       732 | EXPE         |        6 | [EXPE](https://finance.yahoo.com/quote/EXPE/financials)                 |
|  666 |       728 | VEEV         |        6 | [VEEV](https://finance.yahoo.com/quote/VEEV/financials)                 |
|  667 |       727 | UDR          |        6 | [UDR](https://finance.yahoo.com/quote/UDR/financials)                   |
|  696 |       692 | ULTA         |        6 | [ULTA](https://finance.yahoo.com/quote/ULTA/financials)                 |
|  698 |       689 | MDB          |        6 | [MDB](https://finance.yahoo.com/quote/MDB/financials)                   |
|  701 |       686 | HSBC         |        6 | [HSBC](https://finance.yahoo.com/quote/HSBC/financials)                 |
|  746 |       909 | CBOE         |        5 | [CBOE](https://finance.yahoo.com/quote/CBOE/financials)                 |
|  849 |       795 | XLU          |        5 | [XLU](https://finance.yahoo.com/quote/XLU/financials)                   |
|  850 |       794 | VNQ          |        5 | [VNQ](https://finance.yahoo.com/quote/VNQ/financials)                   |
|  930 |      1117 | KEYS         |        4 | [KEYS](https://finance.yahoo.com/quote/KEYS/financials)                 |
